# Generated by Django 4.2.13 on 2024-07-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
